import { BaseModuleEntity } from './../base/baseModuleEntity';
import { SmsMainApiPathCompanyModel } from './smsMainApiCompanyModel';
import { SmsMainApiPathAndCustomerNumberModel } from './smsMainApiPathAndCustomerNumberModel';
import { SmsMainApiPathPermissionModel } from './smsMainApiPathPermissionModel';
import { SmsMainApiPathPriceServiceModel } from './smsMainApiPathPriceServiceModel';
import { SmsMainApiPathSuperSederModel } from './smsMainApiPathSuperSederModel';

export class SmsMainApiPathModel extends BaseModuleEntity<string> {
  Title: string;
  Description?: any;
  ApiDefaultNumber?: any;
  ApiIdentity: number;
  Priority: number;
  PerriodStartWorkTime?: any;
  PerriodEndWorkTime?: any;
  ServerAbilityApiPhoneBook: boolean;
  ServerAbilityApiVoice: boolean;
  ServerConnectionPerMinute: number;
  ServerAbilityMinPack: number;
  ServerAbilityMaxPack: number;
  ApiMinPathNeedToCheckIsOn: boolean;
  ApiMinPathNeedToCheck: number;
  LinkApiPathCompanyId: string;
  // tslint:disable-next-line: variable-name
  virtual_ApiPathCompany: SmsMainApiPathCompanyModel;
  ApiPathCompany: SmsMainApiPathCompanyModel;
  ApiPathCompanyCounterIsOn: boolean;
  ApiAbilitySendUnicodeMessage: boolean;
  ApiAbilitySendNormalMessage: boolean;
  ApiAllowSuperSeder: boolean;
  ApiAbilityUseWebservice: boolean;
  ApiAbilityUseInside: boolean;
  ApiAbilityRegulatorAllowToSend?: any;
  ApiAbilityRegulatorDenayToSend?: any;
  ApiAbilityLengthMinToSend: number;
  ApiAbilityLengthMaxToSend: number;
  ApiPathSuperSeders: SmsMainApiPathSuperSederModel[];
  ApiPathMustSuperSeders: SmsMainApiPathSuperSederModel[];
  ApiPathPermissions: SmsMainApiPathPermissionModel[];
  ApiPathAndApiPathNumbers: SmsMainApiPathAndCustomerNumberModel[];
  ApiPathPriceServices: SmsMainApiPathPriceServiceModel[];
  ApiSendMessageIsOn: boolean;
  ApiSendMessageUrl?: any;
  ApiSendMessageUrlParameter?: any;
  ApiSendMessageMethod: number;
  ApiDeliveryIsOn: boolean;
  ApiDeliveryUrl?: any;
  ApiDeliveryUrlParameter?: any;
  ApiDeliveryMethod: number;
  ApiCreditBackIsOn: boolean;
  ApiCreditBackCheckOnSend?: any;
  ApiCreditBackCheckOnDelivery?: any;
  ApiReciveIsOn: boolean;
  ApiReciveUrl?: any;
  ApiReciveUrlParameter?: any;
  ApiReciveMethod: number;
  ApiInfoCreditCheckIsOn: boolean;
  ApiInfoCreditCheckUrl?: any;
  ApiInfoCreditCheckParameter?: any;
  ApiInfoCreditCheckMethod: number;
  ApiPhoneBookIsOn: boolean;
  ApiPhoneBookUrl?: any;
  ApiPhoneBookMethod: number;
  ApiSendVoiceIsOn: boolean;
  ApiSendVoiceUrl?: any;
  ApiSendVoiceUrlParameter?: any;
  ApiSendVoiceMethod: number;
  ErrorTextToStandBy?: any;
  ErrorTextToDisable?: any;
  ErrorTextToStandByLastGet?: any;
  ErrorTextToStandByLastGetDate?: any;
  ErrorTextToStandByExit: number;
  ErrorTextToDisableLastGet?: any;
  ErrorTextToDisableLastGetDate?: any;
}
